# Generated by Django 3.2 on 2021-05-15 14:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image_uri',
            field=models.ImageField(default=datetime.datetime(2021, 5, 15, 14, 8, 23, 204859, tzinfo=utc), upload_to='media/'),
        ),
    ]
